version: 1.1.1

artifacts:
- path: mugi-query-*.zip
  name: dist
- path: vc_redist.x64.exe
  name: vc_redist

build_script: |
  echo ==================== set env ==================== 
  set VERSION=1.1.1
  call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  set PATH=C:\Qt\5.14.2\msvc2017_64\bin;C:\Qt\Tools\QtCreator\bin\jom;C:\Python39-x64;C:\Python39-x64\Scripts;C:\Qwt-6.2.0\lib;C:\projects\mysql-8.0.27-winx64\lib;C:\Program Files\PostgreSQL\10\bin;%PATH%
  python -m pip install mugideploy
  echo ==================== build qsqlmysql ==================== 
  cd C:\projects
  curl -L -o mysql-8.0.27-winx64.zip https://cdn.mysql.com/Downloads/MySQL-8.0/mysql-8.0.27-winx64.zip
  7z x -y mysql-8.0.27-winx64.zip
  git clone -q --branch 5.14.2 --single-branch --depth=1 git://code.qt.io/qt/qtbase.git
  cd qtbase\src\plugins\sqldrivers
  qmake -- MYSQL_INCDIR="C:/projects/mysql-8.0.27-winx64/include" MYSQL_LIBDIR="C:/projects/mysql-8.0.27-winx64/lib"
  cd mysql
  qmake
  jom install
  echo ==================== build qwt ==================== 
  cd C:\projects
  git clone https://github.com/opencor/qwt.git
  cd qwt
  git checkout -qf 61afb7317ee3283f22dee78143cc6b3f2593f8e3
  qmake
  jom install
  echo ==================== build mugi-query ==================== 
  cd %APPVEYOR_BUILD_FOLDER%
  qmake
  jom release
  mugideploy collect --app mugi-query --version %VERSION% --bin release\mugi-query.exe --no-vcredist --plugins qsqlite qsqlmysql qsqlodbc qsqlpsql
  7z a mugi-query-%VERSION%-win64.zip mugi-query-%VERSION%-win64
  curl -L -o vc_redist.x64.exe https://aka.ms/vs/16/release/vc_redist.x64.exe

deploy:
  description: 'mugi-query'
  provider: GitHub
  auth_token:
    secure: jBN4dQaXdrv9SsDZGZXuGQJ9LlP+jPRXFq++Sbt+qo1dTFGiTIGemBMEazWuPAxc
  on:
    branch: master