// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef RICHHEADERCELL_H
#define RICHHEADERCELL_H
#include <QList>
#include <QString>
class QWidget;
class RichHeaderCellImpl;
typedef QList<RichHeaderCellImpl*> RichHeaderCellList;

class RichHeaderCell {

public:
    RichHeaderCell(RichHeaderCellImpl* impl);
    int row() const;
    RichHeaderCell& row(int value);
    int column() const;
    RichHeaderCell& column(int value);
    int rowSpan() const;
    RichHeaderCell& rowSpan(int value);
    int columnSpan() const;
    RichHeaderCell& columnSpan(int value);
    QString text() const;
    RichHeaderCell& text(const QString& value);
    bool multiline() const;
    RichHeaderCell& multiline(bool value);
    Qt::TextElideMode elide() const;
    RichHeaderCell& elide(Qt::TextElideMode value);
    Qt::Alignment align() const;
    RichHeaderCell& align(Qt::Alignment value);
    double rotation() const;
    RichHeaderCell& rotation(double value);
    QWidget* widget() const;
    RichHeaderCell& widget(QWidget* value);
    bool visible() const;
    RichHeaderCell& visible(bool value);
    int paddingTop() const;
    RichHeaderCell& paddingTop(int value);
    int paddingRight() const;
    RichHeaderCell& paddingRight(int value);
    int paddingBottom() const;
    RichHeaderCell& paddingBottom(int value);
    int paddingLeft() const;
    RichHeaderCell& paddingLeft(int value);
    RichHeaderCell& cell(int row, int column);
    RichHeaderCell& span(int rows, int columns);
    RichHeaderCell& padding(int all);
    RichHeaderCell& padding(int vertical, int horizontal);
    RichHeaderCell& padding(int top, int right, int bottom, int left);
    RichHeaderCell& show();
    RichHeaderCell& hide();
    RichHeaderCell& incColumnSpan();
    RichHeaderCell& incRowSpan();
    RichHeaderCell& moveUp();
    RichHeaderCell& moveDown();
    RichHeaderCell& moveLeft();
    RichHeaderCell& moveRight();

protected:
    RichHeaderCellImpl* mImpl;
};

#endif // RICHHEADERCELL_H
