// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef RICHHEADERDATA_H
#define RICHHEADERDATA_H
#include <QColor>
#include <QList>
class RichHeaderDataImpl;
#include "richheadercell.h"
#include "richheaderdirection.h"

class RichHeaderData {

public:
    RichHeaderData(RichHeaderDataImpl* impl);
    bool multiline() const;
    RichHeaderData& multiline(bool value);
    Qt::TextElideMode elide() const;
    RichHeaderData& elide(Qt::TextElideMode value);
    Qt::Alignment align() const;
    RichHeaderData& align(Qt::Alignment value);
    double rotation() const;
    RichHeaderData& rotation(double value);
    Qt::Orientation tabDirection() const;
    RichHeaderData& tabDirection(Qt::Orientation value);
    bool stretchFixed() const;
    RichHeaderData& stretchFixed(bool value);
    QList<int> subsectionSizes() const;
    RichHeaderData& subsectionSizes(const QList<int>& value);
    QColor highlightColor() const;
    RichHeaderData& highlightColor(const QColor& value);
    bool flatStyle() const;
    RichHeaderData& flatStyle(bool value);
    RichHeaderCell cell(int row, int column);
    bool hasCell(int row, int column);
    RichHeaderData& pull(RichHeaderDirection::DirectionType direction, int sectionCount);
    RichHeaderData& clear();
    RichHeaderData& pullUp(int sectionCount);
    RichHeaderData& pullDown(int sectionCount);
    RichHeaderData& pullLeft(int sectionCount);
    RichHeaderData& pullRight(int sectionCount);

protected:
    RichHeaderDataImpl* mImpl;
};

#endif // RICHHEADERDATA_H
