// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef RICHHEADERDATAIMPL_H
#define RICHHEADERDATAIMPL_H
#include "richheadercell.h"
#include "richheaderdata.h"
#include "richheaderdataimplbase.h"
#include <QColor>
#include <QList>

class RichHeaderDataImpl : public RichHeaderDataImplBase {

public:
    RichHeaderDataImpl();
    RichHeaderCell cell(int row, int column);
    void pullUp(int sectionCount);
    void pullDown(int sectionCount);
    void pullLeft(int sectionCount);
    void pullRight(int sectionCount);
    bool multiline() const;
    void multiline(bool value);
    Qt::TextElideMode elide() const;
    void elide(Qt::TextElideMode value);
    Qt::Alignment align() const;
    void align(Qt::Alignment value);
    double rotation() const;
    void rotation(double value);
    Qt::Orientation tabDirection() const;
    void tabDirection(Qt::Orientation value);
    bool stretchFixed() const;
    void stretchFixed(bool value);
    QList<int> subsectionSizes() const;
    void subsectionSizes(const QList<int>& value);
    QColor highlightColor() const;
    void highlightColor(const QColor& value);
    bool flatStyle() const;
    void flatStyle(bool value);

protected:
    bool mMultiline;
    Qt::TextElideMode mElide;
    Qt::Alignment mAlign;
    double mRotation;
    Qt::Orientation mTabDirection;
    bool mStretchFixed;
    QColor mHighlightColor;
    bool mFlatStyle;
};

#endif // RICHHEADERDATAIMPL_H
