#ifndef DRIVERNAMES_H
#define DRIVERNAMES_H

#define DRIVER_MYSQL "QMYSQL"
#define DRIVER_MARIADB "QMARIADB"
#define DRIVER_SQLITE "QSQLITE"
#define DRIVER_ODBC "QODBC"
#define DRIVER_PSQL "QPSQL"

#endif // DRIVERNAMES_H
