name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Miniconda\Scripts;C:\Miniconda;%PATH%
        pip install mugicli
        pip install aqtinstall
        aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810 -O C:\Qt
        aqt install-qt windows desktop 5.15.2 win64_mingw81 -O C:\Qt
        pyfind C:\Qt -iname qmake.exe gcc.exe qsqlpsql.dll
        curl -L -o qsqlmysql-qt5.15.2-mingw8.1.0-x86_64.zip https://github.com/mugiseyebrows/qsqlmysql-builds/releases/download/5.15.2/qsqlmysql-qt5.15.2-mingw8.1.0-x86_64.zip
        "C:\Program Files\Git\usr\bin\file.exe" C:\mysql\bin\libmysql.dll
